// Code generated by "stringer -type=OpState -output=op_state_string.go"; DO NOT EDIT.

package operation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpStateUnknown-0]
	_ = x[OpStateQueued-1]
	_ = x[OpStateLoading-2]
	_ = x[OpStateLoaded-3]
}

const _OpState_name = "OpStateUnknownOpStateQueuedOpStateLoadingOpStateLoaded"

var _OpState_index = [...]uint8{0, 14, 27, 41, 54}

func (i OpState) String() string {
	if i >= OpState(len(_OpState_index)-1) {
		return "OpState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpState_name[_OpState_index[i]:_OpState_index[i+1]]
}
