// Code generated by "stringer -type=OpType -output=op_type_string.go"; DO NOT EDIT.

package operation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpTypeUnknown-0]
	_ = x[OpTypeGetTerraformVersion-1]
	_ = x[OpTypeGetInstalledTerraformVersion-2]
	_ = x[OpTypeObtainSchema-3]
	_ = x[OpTypeParseModuleConfiguration-4]
	_ = x[OpTypeParseVariables-5]
	_ = x[OpTypeParseModuleManifest-6]
	_ = x[OpTypeParseTerraformSources-7]
	_ = x[OpTypeLoadModuleMetadata-8]
	_ = x[OpTypeDecodeReferenceTargets-9]
	_ = x[OpTypeDecodeReferenceOrigins-10]
	_ = x[OpTypeDecodeVarsReferences-11]
	_ = x[OpTypeGetModuleDataFromRegistry-12]
	_ = x[OpTypeParseProviderVersions-13]
	_ = x[OpTypePreloadEmbeddedSchema-14]
	_ = x[OpTypeStacksPreloadEmbeddedSchema-15]
	_ = x[OpTypeSearchPreloadEmbeddedSchema-16]
	_ = x[OpTypeSchemaModuleValidation-17]
	_ = x[OpTypeSchemaStackValidation-18]
	_ = x[OpTypeSchemaSearchValidation-19]
	_ = x[OpTypeSchemaVarsValidation-20]
	_ = x[OpTypeReferenceValidation-21]
	_ = x[OpTypeReferenceStackValidation-22]
	_ = x[OpTypeTerraformValidate-23]
	_ = x[OpTypeParseStackConfiguration-24]
	_ = x[OpTypeParseSearchConfiguration-25]
	_ = x[OpTypeParsePolicyConfiguration-26]
	_ = x[OpTypeLoadPolicyMetadata-27]
	_ = x[OpTypeSchemaPolicyValidation-28]
	_ = x[OpTypeReferencePolicyValidation-29]
	_ = x[OpTypeParsePolicyTestConfiguration-30]
	_ = x[OpTypeLoadPolicyTestMetadata-31]
	_ = x[OpTypeSchemaPolicyTestValidation-32]
	_ = x[OpTypeReferencePolicyTestValidation-33]
	_ = x[OpTypeLoadStackMetadata-34]
	_ = x[OpTypeLoadSearchMetadata-35]
	_ = x[OpTypeLoadStackRequiredTerraformVersion-36]
	_ = x[OpTypeParseTestConfiguration-37]
	_ = x[OpTypeLoadTestMetadata-38]
	_ = x[OpTypeDecodeTestReferenceTargets-39]
	_ = x[OpTypeDecodeTestReferenceOrigins-40]
	_ = x[OpTypeDecodeWriteOnlyAttributes-41]
	_ = x[OpTypeSchemaTestValidation-42]
}

const _OpType_name = "OpTypeUnknownOpTypeGetTerraformVersionOpTypeGetInstalledTerraformVersionOpTypeObtainSchemaOpTypeParseModuleConfigurationOpTypeParseVariablesOpTypeParseModuleManifestOpTypeParseTerraformSourcesOpTypeLoadModuleMetadataOpTypeDecodeReferenceTargetsOpTypeDecodeReferenceOriginsOpTypeDecodeVarsReferencesOpTypeGetModuleDataFromRegistryOpTypeParseProviderVersionsOpTypePreloadEmbeddedSchemaOpTypeStacksPreloadEmbeddedSchemaOpTypeSearchPreloadEmbeddedSchemaOpTypeSchemaModuleValidationOpTypeSchemaStackValidationOpTypeSchemaSearchValidationOpTypeSchemaVarsValidationOpTypeReferenceValidationOpTypeReferenceStackValidationOpTypeTerraformValidateOpTypeParseStackConfigurationOpTypeParseSearchConfigurationOpTypeParsePolicyConfigurationOpTypeLoadPolicyMetadataOpTypeSchemaPolicyValidationOpTypeReferencePolicyValidationOpTypeParsePolicyTestConfigurationOpTypeLoadPolicyTestMetadataOpTypeSchemaPolicyTestValidationOpTypeReferencePolicyTestValidationOpTypeLoadStackMetadataOpTypeLoadSearchMetadataOpTypeLoadStackRequiredTerraformVersionOpTypeParseTestConfigurationOpTypeLoadTestMetadataOpTypeDecodeTestReferenceTargetsOpTypeDecodeTestReferenceOriginsOpTypeDecodeWriteOnlyAttributesOpTypeSchemaTestValidation"

var _OpType_index = [...]uint16{0, 13, 38, 72, 90, 120, 140, 165, 192, 216, 244, 272, 298, 329, 356, 383, 416, 449, 477, 504, 532, 558, 583, 613, 636, 665, 695, 725, 749, 777, 808, 842, 870, 902, 937, 960, 984, 1023, 1051, 1073, 1105, 1137, 1168, 1194}

func (i OpType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpType_index)-1 {
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpType_name[_OpType_index[idx]:_OpType_index[idx+1]]
}
