# Copyright IBM Corp. 2020, 2026
# SPDX-License-Identifier: MPL-2.0

changesDir: .changes
unreleasedDir: unreleased
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.VersionNoPrefix}} ({{.Time.Format "02 January 2006"}})'
kindFormat: '{{.Kind}}:'
changeFormat: '* {{.Body}} ([{{- if not (eq .Custom.Repository "terraform-ls")}}{{.Custom.Repository}}{{- end}}#{{.Custom.Issue}}](https://github.com/hashicorp/{{.Custom.Repository}}/issues/{{.Custom.Issue}}))'
custom:
  - key: Repository
    label: Repository
    type: enum
    enumOptions:
      - terraform-ls
      - terraform-schema
      - hcl-lang
  - key: Issue
    label: Issue/PR Number
    type: int
    minInt: 1
kinds:
- label: ENHANCEMENTS
  auto: minor
- label: BUG FIXES
  auto: patch
- label: INTERNAL
  auto: patch
- label: NOTES
  auto: patch
- label: BREAKING CHANGES
  auto: minor
newlines:
  afterKind: 1
  beforeKind: 1
  endOfVersion: 2
envPrefix: CHANGIE_
