env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go test ./...

builds:
  -
    id: signable
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
      - -tags=preloadschema
    ldflags:
      - '-s -w -X "main.version={{ .RawVersion }}" -X "main.prerelease={{ if .IsSnapshot }}snapshot.{{ .ShortCommit }}{{ else }}{{ .Prerelease }}{{ end }}"'
    goarch:
      - '386'
      - amd64
      - arm64
    goos:
      - darwin
      - windows
    ignore:
      - goarch: '386'
        goos: darwin
    hooks:
      post: |
        docker run
          -e ARTIFACTORY_TOKEN={{ .Env.ARTIFACTORY_TOKEN }}
          -e ARTIFACTORY_USER={{ .Env.ARTIFACTORY_USER }}
          -e CIRCLE_TOKEN={{ .Env.CIRCLE_TOKEN }}
          -v {{ dir .Path }}:/workdir
          {{ .Env.CODESIGN_IMAGE }}
          sign -product-name={{ .ProjectName }} {{ .Name }}
  -
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
      - -tags=preloadschema
    ldflags:
      - '-s -w -X "main.version={{ .RawVersion }}" -X "main.prerelease={{ if .IsSnapshot }}snapshot.{{ .ShortCommit }}{{ else }}{{ .Prerelease }}{{ end }}"'
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goos:
      - freebsd
      - openbsd
      - linux
      - solaris
    ignore:
      - goarch: '386'
        goos: darwin
      - goarch: arm
        goos: openbsd
      - goarch: arm64
        goos: openbsd
      - goarch: arm64
        goos: freebsd

archives:
  -
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false
    files: # Avoid packaging any extra (default) files
      - none*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  -
    id: with_key_id
    # TODO: Replace with variable once signore provides the primary_key_id
    signature: "${artifact}.72D7468F.sig"
    cmd: signore
    args: ["sign", "--dearmor", "--file", "${artifact}", "--out", "${signature}"]
    artifacts: checksum
  -
    id: default
    signature: "${artifact}.sig"
    cmd: signore
    args: ["sign", "--dearmor", "--file", "${artifact}", "--out", "${signature}"]
    artifacts: checksum

brews:
  -
    tap:
      owner: hashicorp
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    skip_upload: auto
    url_template: "https://releases.hashicorp.com/terraform-ls/{{ .Version }}/{{ .ArtifactName }}"
    commit_author:
      name: hc-espd-packager
      email: team-product-delivery@hashicorp.com
    folder: Formula
    homepage: "https://github.com/hashicorp/terraform-ls"
    description: "Terraform Language Server"
    conflicts:
      - terraform-ls
    install: |
      bin.install "terraform-ls"
    test: |
      system "#{bin}/terraform-ls --version"

publishers:
  - name: upload
    checksum: true
    signature: true
    env:
      - HC_RELEASES_HOST={{ .Env.HC_RELEASES_HOST }}
      - HC_RELEASES_KEY={{ .Env.HC_RELEASES_KEY }}
    cmd: |
      hc-releases upload -product {{ .ProjectName }} -version {{ .Version }} -file={{ .ArtifactPath }}

milestones:
  - name_template: "{{ .Tag }}"
    close: true

release:
  prerelease: auto

changelog:
  skip: true
