// Code generated by "stringer -type=State -output=jobs_state_string.go"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateQueued-0]
	_ = x[StateRunning-1]
	_ = x[StateDone-2]
}

const _State_name = "StateQueuedStateRunningStateDone"

var _State_index = [...]uint8{0, 11, 23, 32}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
