// Code generated by "stringer -type=PathState -output=path_state_string.go"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PathStateQueued-0]
	_ = x[PathStateWalking-1]
}

const _PathState_name = "PathStateQueuedPathStateWalking"

var _PathState_index = [...]uint8{0, 15, 31}

func (i PathState) String() string {
	if i >= PathState(len(_PathState_index)-1) {
		return "PathState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathState_name[_PathState_index[i]:_PathState_index[i+1]]
}
